### ISSUE TITLE
Implement methods for Company resource

### ISSUE THREAD

**Issue by wnuqui** [psyfear/promisepay_ex#8]
Reference: https://reference.assemblypayments.com/#companies

## Todos
- [x] [Create Company](https://reference.assemblypayments.com/#create-company)
- [x] [List Companies](https://reference.assemblypayments.com/#list-companies)
- [x] [Show Company](https://reference.assemblypayments.com/#show-company)
- [x] [Update Company](https://reference.assemblypayments.com/#update-company)

**Comment by wnuqui** [comment]
Done here: https://github.com/psyfear/promisepay_ex/pull/16!
